name : "Test"

on :
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses : actions/checkout@v6
        with:
          node-version : 20
          token: ${{ secrets.PAT }}
          fetch-depth: 0
        env:
          GITHUB_TOKEN : ${{secrets.PAT}}

      - name : Installing Dependencies
        run : |
          npm i

      - name : migrate prisma
        run : |
          npx prisma migrate deploy

      - name : Starting app
        run : |
          npm run start &
          
          PID=$!
          sleep 5

  

      - name : Creation de jeu test
        run : |
          curl -v http://localhost:8080/api/test/3630/createGame

      - name : Création d'éditeur test
        run : |
          curl http://localhost:8080/api/test/3630/createEditor

      - name : Stopping test
        run : |
          kill "$PID"
