name : "Test"

on :
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses : actions/checkout@v6
        with:
          node-version : 20
          token: ${{ secrets.PAT }}
          fetch-depth: 0
        env:
          GITHUB_TOKEN : ${{secrets.PAT}}

      - name : Installing Dependencies
        run : |
          npm i

      - name : Installing CURL
        run : |
          sudo apt install curl

      - name : migrate prisma
        run : |
          npx prisma migrate deploy


      - name : Starting app
        run : |
          npm run start &
          PID=$!

      - name : Creation de film test
        run : |
          curl -X GET -d "http://localhost:8080/api/test/3630/createGame"

      - name : Create d'Ã©diteur test
        run : |
          curl -X GET -d "http://localhost:8080/api/test/3630/createEditor"

      - name : Stopping test
        run : |
          kill -9 $PID
